---
version: "3.9"
services:
  prism:
    image: stoplight/prism:4
    command: "mock -h 0.0.0.0 /api-with-examples.yaml"
    volumes:
      - ./api-with-examples.yaml:/api-with-examples.yaml:ro
    ports:
      # Serve the mocked API locally as available on port 8080
      - "4010:4010"
